Do not include `spatialgradient.cpp`, because Visual Studio 2022 has some problem compiling it:
```
C:\a\1\s\3rdparty\opencv-build-vs\opencv\modules\imgproc\src\spatialgradient.cpp(302): fatal  error C1001: Internal compiler error. [C:\a\1\s\3rdparty\opencv-build-vs\opencv.vcxproj]
  (compiler file 'D:\a\_work\1\s\src\vctools\Compiler\Utc\src\p2\main.c', line 224)
   To work around this problem, try simplifying or changing the program near the locations listed above.
  If possible please provide a repro here: https://developercommunity.visualstudio.com
  Please choose the Technical Support command on the Visual C++
   Help menu, or open the Technical Support help file for more information
```